# 파이썬과 오픈 소스정리

넘파이 모듈 불러오기 정리

In [3]:
import numpy as np
#균일한 간격으로 데이터 생성
a = np.linspace(0,1,5)
print(a)
b=np.arange(0, 10, 2, np.float)
print(b)


[0.   0.25 0.5  0.75 1.  ]
[0. 2. 4. 6. 8.]
()


In [1]:
import numpy as np
a = np.arange(1,7).reshape(2,3)
print(a)
b=np.arange(7,13).reshape(3,2)
print(b)
c=a.dot(b)
print(c)

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]
[[ 58  64]
 [139 154]]


step function

In [1]:
def step_function(x):
    return np.array(x>0, dtype=np.int)

sigmoid

In [4]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

ReLU

In [5]:
def relu(x):
    return np.maximum(0,x)

softmax function

In [10]:
def soft(x):
    return exp(x)/np.sum(exp(x))

# 탄젠트 함수
def tan(x):
    return np.tan.h(x)

평균제곱 오차 (MSE)

In [7]:
def mse(y,t):
    return 0.5*np.sum((y-t)**2)

교차 엔트로피 오차

In [8]:
def cross_entropy(y,t):
    delta=1e-7
    return -np.sum(t*np.log(y+delta)) 

역전파

In [11]:
class mulLayer:
    def __init__(self):
        self.x=None
        self.y=None
    def forward(self,x,y):
        self.x=x
        self.y=y
        out=x*y
        return out
    def backward(self,dout):
        dx=self.x*dout
        dy=self.y*dout
        return dx,dy
    

ReLU 활성화 함수

In [1]:
class relu:
    def __init__(self):
        self.mask=None
    def forward(self,x):
        self.mask=(x<=0)
        out      =x.copy()
        out[self.mask]=0
        return out
    def backward(self,dout):
        dout[self.mask]=0
        dx=dout
        return dx
    

Affine 계층

In [3]:
class Afiine:
    def __init__(self,W,b):
        self.W=w
        self.b=b
        self.x=x
        self.dW=None
        self.db=None
    def forward(self,x):
        self.x=x
        out=np.dot(x,self.W)+self.b
        return out
    def backward(self,dout):
        dx=np.dot(dout,self.W.T)
        self.dw=np.dot(self.X.T,dout)
        self.db=np.dot(dout,axis=0)
        

Affine 계층

In [5]:
class Affine:
    def __init__(self):
        self.out=None
    def forward(self,x):
        out = 1/(1+np.exp(-x))
        self.out = out
        return out
    def backward(self,dout):
        dx = dout*(1.0-self.out)*self.out
        return dx

sigmoid 함수

In [8]:
class sigmoid:
    def __init__(self):
        self.out=None
    def forward(self,x):
        out=1/(1+exp(-x))
        self.out=out
        return out
    def backward(self,dout):
        dx=dout*(1.0-self.out)*self.out
        return dx
    